[package]
name = "video-merger-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
video-merger-core.workspace = true

tokio.workspace = true
tokio-util.workspace = true
futures.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
ffmpeg-next.workspace = true
image.workspace = true
cpal.workspace = true
ringbuf.workspace = true
num_cpus.workspace = true
wgpu.workspace = true
